<a href="https://colab.research.google.com/github/naseemfiver/intro_sentimental_analysis/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
#data loading
#df = pd.read_csv('/content/drive/MyDrive/pandas-master/pokemon_data.txt',delimiter='\t')
#df = pd.read_excel('/content/drive/MyDrive/pandas-master/pokemon_data.xlsx')
df = pd.read_csv('/content/drive/MyDrive/pandas-master/pokemon_data.csv')

In [4]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

Reading data in pandas

In [5]:
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [6]:
#print(df[['Name','Type 2']][0:5])
#df.Name[0:5]
i=0
print(df[[x for x in df.columns ]][0:5])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [7]:
#print(df.iloc[3])

In [12]:
for index,a in df.iterrows():
  print(index,a['Type 1'])

0 Grass
1 Grass
2 Grass
3 Grass
4 Fire
5 Fire
6 Fire
7 Fire
8 Fire
9 Water
10 Water
11 Water
12 Water
13 Bug
14 Bug
15 Bug
16 Bug
17 Bug
18 Bug
19 Bug
20 Normal
21 Normal
22 Normal
23 Normal
24 Normal
25 Normal
26 Normal
27 Normal
28 Poison
29 Poison
30 Electric
31 Electric
32 Ground
33 Ground
34 Poison
35 Poison
36 Poison
37 Poison
38 Poison
39 Poison
40 Fairy
41 Fairy
42 Fire
43 Fire
44 Normal
45 Normal
46 Poison
47 Poison
48 Grass
49 Grass
50 Grass
51 Bug
52 Bug
53 Bug
54 Bug
55 Ground
56 Ground
57 Normal
58 Normal
59 Water
60 Water
61 Fighting
62 Fighting
63 Fire
64 Fire
65 Water
66 Water
67 Water
68 Psychic
69 Psychic
70 Psychic
71 Psychic
72 Fighting
73 Fighting
74 Fighting
75 Grass
76 Grass
77 Grass
78 Water
79 Water
80 Rock
81 Rock
82 Rock
83 Fire
84 Fire
85 Water
86 Water
87 Water
88 Electric
89 Electric
90 Normal
91 Normal
92 Normal
93 Water
94 Water
95 Poison
96 Poison
97 Water
98 Water
99 Ghost
100 Ghost
101 Ghost
102 Ghost
103 Rock
104 Psychic
105 Psychic
106 Water
107 Water
108 Electric
109 Electric
110 Grass
111 Grass
112 Ground
113 Ground
114 Fighting
115 Fighting
116 Normal
117 Poison
118 Poison
119 Ground
120 Ground
121 Normal
122 Grass
123 Normal
124 Normal
125 Water
126 Water
127 Water
128 Water
129 Water
130 Water
131 Psychic
132 Bug
133 Ice
134 Electric
135 Fire
136 Bug
137 Bug
138 Normal
139 Water
140 Water
141 Water
142 Water
143 Normal
144 Normal
145 Water
146 Electric
147 Fire
148 Normal
149 Rock
150 Rock
151 Rock
152 Rock
153 Rock
154 Rock
155 Normal
156 Ice
157 Electric
158 Fire
159 Dragon
160 Dragon
161 Dragon
162 Psychic
163 Psychic
164 Psychic
165 Psychic
166 Grass
167 Grass
168 Grass
169 Fire
170 Fire
171 Fire
172 Water
173 Water
174 Water
175 Normal
176 Normal
177 Normal
178 Normal
179 Bug
180 Bug
181 Bug
182 Bug
183 Poison
184 Water
185 Water
186 Electric
187 Fairy
188 Normal
189 Fairy
190 Fairy
191 Psychic
192 Psychic
193 Electric
194 Electric
195 Electric
196 Electric
197 Grass
198 Water
199 Water
200 Rock
201 Water
202 Grass
203 Grass
204 Grass
205 Normal
206 Grass
207 Grass
208 Bug
209 Water
210 Water
211 Psychic
212 Dark
213 Dark
214 Water
215 Ghost
216 Psychic
217 Psychic
218 Normal
219 Bug
220 Bug
221 Normal
222 Ground
223 Steel
224 Steel
225 Fairy
226 Fairy
227 Water
228 Bug
229 Bug
230 Bug
231 Bug
232 Bug
233 Dark
234 Normal
235 Normal
236 Fire
237 Fire
238 Ice
239 Ice
240 Water
241 Water
242 Water
243 Ice
244 Water
245 Steel
246 Dark
247 Dark
248 Dark
249 Water
250 Ground
251 Ground
252 Normal
253 Normal
254 Normal
255 Fighting
256 Fighting
257 Ice
258 Electric
259 Fire
260 Normal
261 Normal
262 Electric
263 Fire
264 Water
265 Rock
266 Rock
267 Rock
268 Rock
269 Psychic
270 Fire
271 Psychic
272 Grass
273 Grass
274 Grass
275 Grass
276 Fire
277 Fire
278 Fire
279 Fire
280 Water
281 Water
282 Water
283 Water
284 Dark
285 Dark
286 Normal
287 Normal
288 Bug
289 Bug
290 Bug
291 Bug
292 Bug
293 Water
294 Water
295 Water
296 Grass
297 Grass
298 Grass
299 Normal
300 Normal
301 Water
302 Water
303 Psychic
304 Psychic
305 Psychic
306 Psychic
307 Bug
308 Bug
309 Grass
310 Grass
311 Normal
312 Normal
313 Normal
314 Bug
315 Bug
316 Bug
317 Normal
318 Normal
319 Normal
320 Fighting
321 Fighting
322 Normal
323 Rock
324 Normal
325 Normal
326 Dark
327 Dark
328 Steel
329 Steel
330 Steel
331 Steel
332 Steel
333 Steel
334 Fighting
335 Fighting
336 Fighting
337 Electric
338 Electric
339 Electric
340 Electric
341 Electric
342 Bug
343 Bug
344 Grass
345 Poison
346 Poison
347 Water
348 Water
349 Water
350 Water
351 Water
352 Fire
353 Fire
354 Fire
355 Fire
356 Psychic
357 Psychic
358 Normal
359 Ground
360 Ground
361 Ground
362 Grass
363 Grass
364 Normal
365 Dragon
366 Dragon
367 Normal
368 Poison
369 Rock
370 Rock
371 Water
372 Water
373 Water
374 Water
375 Ground
376 Ground
377 Rock
378 Rock
379 Rock
380 Rock
381 Water
382 Water
383 Normal
384 Normal
385 Ghost
386 Ghost
387 Ghost
388 Ghost
389 Ghost
390 Grass
391 Psychic
392 Dark
393 Dark
394 Psychic
395 Ice
396 Ice
397 Ice
398 Ice
399 Ice
400 Ice
401 Water
402 Water
403 Water
404 Water
405 Water
406 Dragon
407 Dragon
408 Dragon
409 Dragon
410 Steel
411 Steel
412 Steel
413 Steel
414 Rock
415 Ice
416 Steel
417 Dragon
418 Dragon
419 Dragon
420 Dragon
421 Water
422 Water
423 Ground
424 Ground
425 Dragon
426 Dragon
427 Steel
428 Psychic
429 Psychic
430 Psychic
431 Psychic
432 Grass
433 Grass
434 Grass
435 Fire
436 Fire
437 Fire
438 Water
439 Water
440 Water
441 Normal
442 Normal
443 Normal
444 Normal
445 Normal
446 Bug
447 Bug
448 Electric
449 Electric
450 Electric
451 Grass
452 Grass
453 Rock
454 Rock
455 Rock
456 Rock
457 Bug
458 Bug
459 Bug
460 Bug
461 Bug
462 Bug
463 Bug
464 Electric
465 Water
466 Water
467 Grass
468 Grass
469 Water
470 Water
471 Normal
472 Ghost
473 Ghost
474 Normal
475 Normal
476 Normal
477 Ghost
478 Dark
479 Normal
480 Normal
481 Psychic
482 Poison
483 Poison
484 Steel
485 Steel
486 Rock
487 Psychic
488 Normal
489 Normal
490 Ghost
491 Dragon
492 Dragon
493 Dragon
494 Dragon
495 Normal
496 Fighting
497 Fighting
498 Fighting
499 Ground
500 Ground
501 Poison
502 Poison
503 Poison
504 Poison
505 Grass
506 Water
507 Water
508 Water
509 Grass
510 Grass
511 Grass
512 Dark
513 Electric
514 Normal
515 Ground
516 Grass
517 Electric
518 Fire
519 Fairy
520 Bug
521 Grass
522 Ice
523 Ground
524 Ice
525 Normal
526 Psychic
527 Psychic
528 Rock
529 Ghost
530 Ice
531 Electric
532 Electric
533 Electric
534 Electric
535 Electric
536 Electric
537 Psychic
538 Psychic
539 Psychic
540 Steel
541 Water
542 Fire
543 Normal
544 Ghost
545 Ghost
546 Psychic
547 Water
548 Water
549 Dark
550 Grass
551 Grass
552 Normal
553 Psychic
554 Grass
555 Grass
556 Grass
557 Fire
558 Fire
559 Fire
560 Water
561 Water
562 Water
563 Normal
564 Normal
565 Normal
566 Normal
567 Normal
568 Dark
569 Dark
570 Grass
571 Grass
572 Fire
573 Fire
574 Water
575 Water
576 Psychic
577 Psychic
578 Normal
579 Normal
580 Normal
581 Electric
582 Electric
583 Rock
584 Rock
585 Rock
586 Psychic
587 Psychic
588 Ground
589 Ground
590 Normal
591 Normal
592 Fighting
593 Fighting
594 Fighting
595 Water
596 Water
597 Water
598 Fighting
599 Fighting
600 Bug
601 Bug
602 Bug
603 Bug
604 Bug
605 Bug
606 Grass
607 Grass
608 Grass
609 Grass
610 Water
611 Ground
612 Ground
613 Ground
614 Fire
615 Fire
616 Fire
617 Grass
618 Bug
619 Bug
620 Dark
621 Dark
622 Psychic
623 Ghost
624 Ghost
625 Water
626 Water
627 Rock
628 Rock
629 Poison
630 Poison
631 Dark
632 Dark
633 Normal
634 Normal
635 Psychic
636 Psychic
637 Psychic
638 Psychic
639 Psychic
640 Psychic
641 Water
642 Water
643 Ice
644 Ice
645 Ice
646 Normal
647 Normal
648 Electric
649 Bug
650 Bug
651 Grass
652 Grass
653 Water
654 Water
655 Water
656 Bug
657 Bug
658 Grass
659 Grass
660 Steel
661 Steel
662 Steel
663 Electric
664 Electric
665 Electric
666 Psychic
667 Psychic
668 Ghost
669 Ghost
670 Ghost
671 Dragon
672 Dragon
673 Dragon
674 Ice
675 Ice
676 Ice
677 Bug
678 Bug
679 Ground
680 Fighting
681 Fighting
682 Dragon
683 Ground
684 Ground
685 Dark
686 Dark
687 Normal
688 Normal
689 Normal
690 Dark
691 Dark
692 Fire
693 Bug
694 Dark
695 Dark
696 Dark
697 Bug
698 Bug
699 Steel
700 Rock
701 Grass
702 Flying
703 Flying
704 Electric
705 Electric
706 Dragon
707 Dragon
708 Ground
709 Ground
710 Dragon
711 Dragon
712 Dragon
713 Water
714 Water
715 Normal
716 Normal
717 Bug
718 Grass
719 Grass
720 Grass
721 Fire
722 Fire
723 Fire
724 Water
725 Water
726 Water
727 Normal
728 Normal
729 Normal
730 Fire
731 Fire
732 Bug
733 Bug
734 Bug
735 Fire
736 Fire
737 Fairy
738 Fairy
739 Fairy
740 Grass
741 Grass
742 Fighting
743 Fighting
744 Normal
745 Psychic
746 Psychic
747 Psychic
748 Steel
749 Steel
750 Steel
751 Steel
752 Fairy
753 Fairy
754 Fairy
755 Fairy
756 Dark
757 Dark
758 Rock
759 Rock
760 Poison
761 Poison
762 Water
763 Water
764 Electric
765 Electric
766 Rock
767 Rock
768 Rock
769 Rock
770 Fairy
771 Fighting
772 Electric
773 Rock
774 Dragon
775 Dragon
776 Dragon
777 Steel
778 Ghost
779 Ghost
780 Ghost
781 Ghost
782 Ghost
783 Ghost
784 Ghost
785 Ghost
786 Ghost
787 Ghost
788 Ice
789 Ice
790 Flying
791 Flying
792 Fairy
793 Dark
794 Dragon
795 Rock
796 Rock
797 Psychic
798 Psychic
799 Fire

In [9]:
for index, row in df.iterrows():
  print(index,row['Name'] )

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 Flabébé
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

In [26]:
 df.loc[df['Legendary']==True]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [27]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,738.00000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000,738.000000
mean,367.45393,435.158537,69.081301,79.040650,73.960705,72.733062,71.674797,68.668022,3.356369
std,208.07444,120.519108,25.532407,32.432014,31.568492,32.760436,27.823146,29.798137,1.664244
min,2.00000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000
25%,192.25000,330.000000,50.000000,55.000000,50.000000,48.000000,50.000000,48.000000,2.000000
50%,372.50000,450.000000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.000000
75%,546.75000,515.000000,80.000000,100.000000,90.000000,95.000000,90.000000,91.000000,5.000000
max,721.00000,780.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.000000

In [15]:
df.sort_values(["Name",'HP'], ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [16]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [17]:
df['Total'] = df['HP']+df['Attack']

In [18]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,94
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,122
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,162
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,180
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,91

In [19]:
#df = df.drop(columns = ['Total'])
#df

df['Total'] = df.iloc[:,4:10].sum(axis =1)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [20]:
#df = df[['Total','HP','Defense']]
#df.head()

In [21]:
cols = list(df.columns.values)
df = df[cols[:4]+[cols[-1]]+cols[4:12]]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [24]:
df = df.drop(df.index[df['Speed'].isin([45])])
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True